### ISSUE TITLE
where is vendor?

### ISSUE THREAD

**Issue by icakir** [wheatbin/wheatbin#1]
app/common.php  

couldnt find 

require **DIR**.'/../vendor/autoload.php';

it isnt in git repo..

**Comment by jasonscomely** [comment]
Hi icakir! Thanks for reaching out and participating. I put a lot of blood, sweat and (even more) tears into Wheatbin, so I hope you enjoy it. 

As for your question: I don't have a definitive answer for you (yet)  Once things settle down and I have some free time I'll try to fix any outstanding issues.  

With that said, if you can solve this problem and help Wheatbin get even better, knock yourself out brother! Wheatbin is for everyone. 

Again, thank you for your comment and participation!

**Comment by wheatbin** [comment]
Also: I suck at programming, and I got a lot of help from people far smarter than me to get Wheatbin to this point. Please have patience with me as I muddle along. 

And again, any help you can offer will be much appreciated.

**Comment by wheatbin** [comment]
Thanks again for the heads up. While I figure things out, here is a direct download link to [wheatbin.zip](https://yadi.sk/d/QTG5jMZmrpY7T).

**Comment by jasonscomely** [comment]
The vendor directory has been added and the installation instructions have been revised.
